version: "3.8"

services:
  db:
    image: postgres:16.1-alpine
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - /var/data/postgres/:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
