# Use official Node.js image as the base
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm

# Copy only package.json and lock file first for caching dependencies
COPY . ./

# Install dependencies
RUN pnpm install --frozen-lockfile

# Command to run your application
CMD ["pnpm", "dev"]
